### ISSUE TITLE
Spring boot version should be fixed by Spring Cloud

### ISSUE THREAD

**Issue by dsyer** [dsyer/cloud-initializr#3]
There is still a drop down to select the Spring Boot version, but actually it doesn't make any sense to use a version that isn't managed by Spring Cloud. A drop down to select the Cloud version would be good, but then the version ranges in the metadata would be useless or misleading.

**Comment by snicoll** [comment]
Ah, interesting.

The problem, really is that the parameter is named `bootVersion` in the meta-data but nothing actually prevents you to have a `cloudVersion` that overrides this somehow. As for the versionRange, you need to adapt your instance config since that'd become the spring cloud version range in that case. 

I think we can make that work.
